# Generated by Django 5.2.1 on 2025-07-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_me',
            field=models.CharField(
                blank=True, max_length=240, null=True, verbose_name='About author'
            ),
        ),
    ]
