[project]
name = "blog"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.1",
    "pillow>=11.2.1",
    "psycopg[binary]>=3.2.9",
    "python-dotenv>=1.1.0",
]
