# Generated by Django 5.2.1 on 2025-06-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0003_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
