# Generated by Django 5.2.1 on 2025-06-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
