# Generated by Django 5.2.1 on 2025-06-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0005_post_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
        ),
    ]
