# Generated by Django 5.2.1 on 2025-06-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0008_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
