# Generated by Django 5.2.1 on 2025-06-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0010_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
