# Generated by Django 5.2.1 on 2025-06-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0013_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=70, unique=True),
        ),
    ]
